[remain]
10.152.19.12

[remain:vars]
ansible_user=redhat
#ansible_user=user
#ansible_user=atiadmin
#ansible_user=mk7
#ansible_user=root
#ansible_user=azadmin
ansible_become_user=root
#ansible_become_pass=@ristocrat123
#ansible_become_pass=2Hard2Guess
ansible_become_pass=H#av#nh#!!@1990
#ansible_become_pass=palmedia1
#ansible_become_pass=mk7
#ansible_become_pass=IottAR4EQmXbSoICz6UA
ansible_become=true
<<<<<<< Updated upstream
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
=======
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
>>>>>>> Stashed changes
